# Generated by Django 5.1.6 on 2025-03-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Sub-Manager', 'Sub-Manager'), ('Officer', 'Officer')], default='Officer', max_length=20),
        ),
    ]
